### PR TITLE
Retrieve phpType Attribute from Cast, Fallback to Column Type

### PR DESCRIPTION
**Pull request by clementbirkle**
Currently, the `phpType` is determined solely based on the column type. However, it should also consider the cast type and fall back to the column type if the cast is not present.

For instance, a column type `string` can be cast to a boolean. In this case, the `phpType` should be `bool` rather than `string`.

Please note that this PR introduces a breaking change.

Additionally, I have changed the return type from `DateTime` to the fully qualified `DateTimeInterface` interface.

### CODE REVIEW

**Comment by freekmurze** [comment]
> Please note that this PR introduces a breaking change.

Could you implement this without making a breaking change?

**Comment by clementbirkle** [comment]
The breaking change pertains only to the return type of `phpType`.

Depending on the model's cast attribute/method, `phpType` might return a different value than it did previously.

Perhaps I could return `DateTime` instead of the fully qualified `DateTimeInterface` for dates. Would this be sufficient to consider this PR a non-breaking change?

**Comment by freekmurze** [comment]
> The breaking change pertains only to the return type of phpType.

It could also be seen as a bug fix, right?

**Comment by clementbirkle** [comment]
I wonder if we shouldn't change in this PR `DateTimeInterface` to `CarbonInterface` for better typing. What do you think, @freekmurze?

- https://github.com/spatie/laravel-model-info/pull/42/files#diff-48f2b4eea68da00a2501ad9a2bdae3a0b50929df8cbc1573681590ddf9069963R91
- https://github.com/spatie/laravel-model-info/pull/42/files#diff-48f2b4eea68da00a2501ad9a2bdae3a0b50929df8cbc1573681590ddf9069963R119

**Comment by freekmurze** [comment]
> I wonder if we shouldn't change in this PR DateTimeInterface to CarbonInterface for better typing. What do you think, @freekmurze?

That's fine by me

**Comment by clementbirkle** [comment]
I updated `DateTimeInterface` to `CarbonInterface` for better typing as discussed. Thanks for the input!

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
