### PR TITLE
Add Trait information to model info

### PR DESCRIPTION
**Pull request by Riley19280**
Adds a `traits` property to the model info. Among other purposes, it can be used to tell if a model is using soft deletes.

### CODE REVIEW

**Comment by Riley19280** [comment]
It appears that an empty collection is serialized to a snapshot differently in `stable` vs `lowest` targets. Is there something that can be done about that?

**Comment by freekmurze** [comment]
Feel free to update the required version of the snapshot package to fix this. If that doesn't help, then you should investigate a bit deeper why there are differences.

**Comment by Riley19280** [comment]
Narrowed it down to this
`spatie/phpunit-snapshot-assertions  4.2.8     requires                    symfony/serializer (^4.0|^5.0|^6.0) `
`composer update --prefer-lowest` in the test script installs symfony/serializer v4, which serializes differently than v6.  
Adding the dev requirement `"symfony/serializer": "^6"` to this package does solve the issue, however I am not sure that that is something we want to do here. Thoughts?

**Comment by freekmurze** [comment]
I think it's fine to require v6 of the serializer as dev dependency 👍

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
